### PR TITLE
Fix login redirect

### PR DESCRIPTION
**Pull request by jallman112**

### CODE REVIEW

**Comment by jallman112** [comment]
Hold off on this for a bit. I'll write a test to include with the change

**Comment by jallman112** [comment]
Just to get it to link up #90

**Comment by jallman112** [comment]
I put the new test in the LoginView test case.  Does that make sense, or should it go somewhere else? Maybe functional tests?

**Comment by deeppunster** [comment]
I agree with Jeff about where to put the test.  Thanks Jeff for this fix!

**Pull request merged**
